export const INSERT_COMMENT_TASK_SAGA = 'INSERT_COMMENT_TASK_SAGA';
export const INSERT_COMMENT_TASK = 'INSERT_COMMENT_TASK';

export const DELETE_COMMENT_TASK_SAGA = "DELETE_COMMENT_TASK_SAGA";

export const UPDATE_COMMENT_TASK_SAGA = "UPDATE_COMMENT_TASK_SAGA";